# Generated by Django 4.2.2 on 2023-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='school.student'),
        ),
    ]
